# Generated by Django 4.1.5 on 2023-01-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_store_email_alter_store_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
