# Generated by Django 4.1.5 on 2023-01-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_store_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ost",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Дата регистрации"),
        ),
        migrations.AlterField(
            model_name="store",
            name="debt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Задолженность",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Завод"),
                    (1, "Дилер"),
                    (2, "Розничный магазин"),
                    (3, "ИП"),
                ]
            ),
        ),
    ]
