# Generated by Django 4.1.5 on 2023-01-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_ost_alter_store_created_alter_store_debt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="ost",
        ),
    ]
