# Generated by Django 4.1.5 on 2023-01-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_ost_alter_store_created_alter_store_debt_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="store.store",
                verbose_name="Компания",
            ),
        ),
    ]
